name: Old
on: workflow_dispatch
env:
  DEPLOY_PATH: '/var/www/app'
  SERVER_PORT: 22
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    #- name: Install NodeJs
      #uses: actions/setup-node@v3
      #with:
        #node-version: ${{env.NODE_VERSION}}
        
    #- name: Install Dependencies
      #run: npm ci

    - name: Testing
      run: echo {Testing with $TESTING}
      
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        
    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          .next
          package.json
          package-lock.json
      
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Get build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          
      - name: Output Contents
        run: ls -a

      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SERVER_USERNAME }}
            server: ${{ secrets.SERVER_IP }}
            password: ${{ secrets.SERVER_PASSWORD }}
            ssh_private_key: ${{ secrets.SERVER_SSH_KEY }} 
            local_path: './*'
            remote_path: ${{env.DEPLOY_PATH}}

      - name: Install Dependencies on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{env.SERVER_PORT}}
          script: |
            cd /var/www/app
            npm ci
            pm2 restart 0